theme: minima

author:
  name: Ralph J. McDougall
  email: rjm279@cam.ac.uk
  affiliation: University of Cambridge

title: "Ralph J. McDougall"
description: "PhD student in Statistical Signal Processing"
url: "https://RalphMcDougall.github.io/"
markdown: kramdown

github: RalphMcDougall
linkedin: RalphMcDougall

google_scholar: 83-zNuIAAAAJ 
orcid: 0009-0006-8041-5522

show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
